version: '3'
services:
  redis-7000:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7000", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7000:7000"
    volumes:
      - ./7000:/data
  redis-7001:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7001:7001"
    volumes:
      - ./7001:/data
  # ...repeat for 7002, 7003, 7004, 7005
  redis-7002:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7002:7002"
    volumes:
      - ./7002:/data
  redis-7003:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7003", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7003:7003"
    volumes:
      - ./7003:/data
  redis-7004:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7004", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7004:7004"
    volumes:
      - ./7004:/data
  redis-7005:
    image: redis:7-alpine
    command: ["redis-server", "--port", "7005", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7005:7005"
    volumes:
      - ./7005:/data