version: '3.8'

services:
  cassandra1:
    image: cassandra:5.0
    container_name: cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=cassandra1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9042:9042"
    volumes:
      - cassandra1_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: cassandra:5.0
    container_name: cassandra2
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_LISTEN_ADDRESS=cassandra2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9043:9042"
    volumes:
      - cassandra2_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra3:
    image: cassandra:5.0
    container_name: cassandra3
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - CASSANDRA_LISTEN_ADDRESS=cassandra3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9044:9042"
    volumes:
      - cassandra3_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra4:
    image: cassandra:5.0
    container_name: cassandra4
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra4
      - CASSANDRA_LISTEN_ADDRESS=cassandra4
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9045:9042"
    volumes:
      - cassandra4_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra5:
    image: cassandra:5.0
    container_name: cassandra5
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra5
      - CASSANDRA_LISTEN_ADDRESS=cassandra5
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9046:9042"
    volumes:
      - cassandra5_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5    

  cassandra6:
    image: cassandra:5.0
    container_name: cassandra6
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3,cassandra4,cassandra5,cassandra6
      - CASSANDRA_BROADCAST_ADDRESS=cassandra6
      - CASSANDRA_LISTEN_ADDRESS=cassandra6
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    ports:
      - "9047:9042"
    volumes:
      - cassandra6_data:/var/lib/cassandra
    networks:
      - cassandra_net
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5    

networks:
  cassandra_net:

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data:
  cassandra4_data:
  cassandra5_data:
  cassandra6_data:
